cv_encoder: mlp 
data_source: DrugBank
adapt_before_fusion: false
decoder_lr: 0.001
eps: 0.000001
evaluate_interval: 10
feature_dim: 128
fusion: transformer
fusion_lr: 0.001
gin_batch_norm: true
gin_edge_input_dim: 18
hgt_num_layers: 2
kg_encoder: hgt
kg_encoder_lr: 0.001
loss_fn_name: bce
num_attention_bottlenecks: 4
num_epochs: 800
perturb_encoders_lr: 0.0001
pos_emb_dropout: 0.2
pos_emb_type: sinusoidal
proj_actn: relu
proj_dropout: 0.1
str_encoder: gin
structure_encoder_lr: 0.0001
task: multiclass
test: true
train_with_str_str: false
transformer_actn: gelu
transformer_agg: x-attn
transformer_att_heads: 8
transformer_dropout: 0.3
transformer_ffn_dim: 256
transformer_head_dim: 64
transformer_norm_first: true
transformer_num_layers: 2
tx_chemcpa_config_path: configs/chemcpa/chemcpa_finetune_configs.yaml
tx_encoder: chemcpa
use_modality_pretrain: true
use_pretrained_adaptor: true
warmup_epochs: 100
wd: 0.001 
