seml:
  executable: .
  project_root_dir: .

fixed:
  training.checkpoint_freq: 50                            # checkpoint frequency to run evaluate, and maybe save checkpoint
  training.num_epochs: 300                                # maximum epochs for training. One epoch updates either autoencoder, or adversary, depending on adversary_steps.
  training.max_minutes: 600                              # maximum computation time
  training.full_eval_during_train: True
  training.run_eval_disentangle: False                     # whether to calc the disentanglement loss when running the full eval
  training.run_eval_r2: True
  training.run_eval_logfold: False
  training.save_checkpoints: True                         # checkpoints tend to be ~250MB large for LINCS.
  training.save_dir: model_output/pretrain/adapting/tx/checkpoints/sweep/
  training.run_name: tx_adapting_full_use_drugs_sweep  # can also be "wo_drug"
  
  dataset.data_params.dataset_path: views_features_new/tx/
  dataset.data_params.perturbation_key: canonical_smiles         # stores name of the drug
  dataset.data_params.pert_category: max_dose_averaged_sig_id    # stores smiles_celltype_drugdose
  dataset.data_params.dose_key: pert_dose                      # stores drug dose as a float
  dataset.data_params.covariate_keys: cell_iname           # necessary field for cell types. Fill it with a dummy variable if no celltypes present.
  dataset.data_params.smiles_key: canonical_smiles
  dataset.data_params.use_drugs_idx: True                 # If false, will use One-hot encoding instead
  dataset.data_params.split_key: split
  dataset.data_params.degs_key: null

  model.load_pretrained: False
  model.pretrained_model_path: null
  model.pretrained_model_ckpt: null
  model.hparams.dim: 128
  model.hparams.batch_size: 4096
  model.additional_params.patience: 10 # patience for early stopping. Effective epochs: patience * checkpoint_freq.
  model.additional_params.doser_type: amortized 
  model.additional_params.multi_task: False  # whether to train on DEG prediction or not
  model.additional_params.seed: 42
  model.embedding.directory: views_features_new/tx/embeddings/
  model.embedding.model: rdkit
  model.append_ae_layer: False

random: 
  samples: 100
  seed: 218123
  model.use_drugs:  # whether to encode drugs and use the drug adversary loss or not
    type: choice
    options:
      - True  
      - False
  model.additional_params.decoder_activation:
    type: choice
    options:
      - ReLU
      - linear
  model.hparams.dropout: 
    type: choice
    options:
      - 0.2
      - 0.3
      - 0.4
      - 0.5
  model.hparams.autoencoder_width: 
    type: choice
    options:
      - 128
      - 256
      - 512
  model.hparams.autoencoder_depth: 
    type: choice
    options:
      - 2
      - 3
      - 4
      - 5
  model.hparams.autoencoder_lr:
    type: choice
    options:
      - 1e-3
      - 1e-4
      - 1e-5
  model.hparams.autoencoder_wd:
    type: choice
    options:
      - 1e-7
      - 1e-8
  model.hparams.adversary_width:
    type: choice
    options:
      - 64
      - 128
      - 256
      - 512
  model.hparams.adversary_depth:
    type: choice
    options:
      - 2
      - 3
      - 4
  model.hparams.adversary_lr:
    type: choice
    options:
      - 1e-3
      - 1e-4
      - 1e-5
  model.hparams.adversary_wd:
    type: choice
    options:
      - 1e-7
      - 1e-8
  model.hparams.adversary_steps:            # every X steps, update the adversary INSTEAD OF the autoencoder.
    type: choice
    options:
      - 3
      - 2
  model.hparams.reg_adversary:
    type: choice
    options:
      - 5
      - 10
      - 20
      - 40
      - 80
  model.hparams.reg_adversary_cov:
    type: choice
    options:
      - 5
      - 10
      - 20
      - 40
  model.hparams.penalty_adversary:
    type: choice
    options:
      - 1
      - 2
      - 4
      - 8
  model.hparams.dosers_lr:
    type: choice
    options:
      - 1e-4
      - 1e-3
      - 1e-2
  model.hparams.dosers_wd:
    type: choice
    options: 
      - 1e-8
      - 1e-7
  model.hparams.dosers_width: 
    type: choice
    options:
      - 32
      - 64
      - 128
  model.hparams.dosers_depth: 
    type: choice
    options:
      - 1
      - 2
      - 3
      - 4
  model.hparams.step_size_lr:                 # this applies to all optimizers (AE, ADV, DRUG)
    type: choice
    options:
      - 50
      - 100
      - 200
  model.hparams.embedding_encoder_width: 
    type: choice
    options:
      - 128
      - 256
  model.hparams.embedding_encoder_depth:
    type: choice
    options:
      - 2
      - 3
      - 4
    