cv_encoder: mlp 
data_source: TWOSIDES
adapt_before_fusion: false
decoder_lr: 0.005
eps: 0.000001
evaluate_interval: 10
feature_dim: 128
fusion: transformer
fusion_lr: 0.0005
gin_batch_norm: true
gin_edge_input_dim: 18
hgt_num_layers: 2
kg_encoder: hgt
kg_encoder_lr: 0.0005
loss_fn_name: bce
normalize: false
num_attention_bottlenecks: 2
num_epochs: 800
perturb_encoders_lr: 0.001
pos_emb_dropout: 0.1
pos_emb_type: learnable
proj_actn: relu
proj_dropout: 0.1
str_encoder: gin
structure_encoder_lr: 0.001
task: multilabel
test: true
train_with_str_str: true
transformer_actn: gelu
transformer_agg: x-attn
transformer_att_heads: 2
transformer_dropout: 0.4
transformer_ffn_dim: 512
transformer_head_dim: 256
transformer_norm_first: true
transformer_num_layers: 2
tx_chemcpa_config_path: configs/chemcpa/chemcpa_finetune_configs.yaml
tx_encoder: chemcpa
use_modality_pretrain: true
use_pretrained_adaptor: true
warmup_epochs: 10
wd: 0.001 
